### ISSUE TITLE
NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by Wouter1** [Wouter1/osm-garmin#1]
Sorry bad title, it's getting late...
]
Current mkgmap does not work if you split and mkgmap a "real" map
```
java -jar ../mkgmap.jar --gmapsupp -c template.args 
Time started: Wed Jan 26 22:31:02 CET 2022
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at uk.me.parabola.imgfmt.sys.ImgHeader.createHeader(ImgHeader.java:147)
	at uk.me.parabola.imgfmt.sys.ImgFS.createInitFS(ImgFS.java:372)
	at uk.me.parabola.imgfmt.sys.ImgFS.createFs(ImgFS.java:123)
	at uk.me.parabola.imgfmt.sys.ImgFS.createFs(ImgFS.java:102)
	at uk.me.parabola.imgfmt.app.map.Map.createMap(Map.java:99)
	at uk.me.parabola.mkgmap.main.MapMaker.makeMap(MapMaker.java:98)
	at uk.me.parabola.mkgmap.main.MapMaker.makeMap(MapMaker.java:56)
	at uk.me.parabola.mkgmap.main.Main$1.call(Main.java:290)
	at uk.me.parabola.mkgmap.main.Main$1.call(Main.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Wouter1** [comment]
There appears to be a number of version conflicts in the pom.
1. xerces 4.11 conflicts with geotools that uses some sublibrary of xerces 2.4.0 internally
2. jdom b9 can't beused because geotools uses jdom 1.0
3. junit 4.11 can't be used because some genius at xpp3 hard included junit 4.7 in their distro...
But after replacing all these libraries with older libraries, the junit test fial
. 5 errors 22 warnings, errors like

java.lang.NoClassDefFoundError: Could not initialize class uk.me.parabola.mkgmap.build.LocatorConfig


java.lang.UnsupportedOperationException:  setXIncludeAware is not supported on this JAXP implementation or earlier: class org.apache.xerces.jaxp.SAXParserFactoryImpl

**Comment by Wouter1** [comment]
Fixed the dependency conflicts by ecluding xerces from geotools and including a different working version

**Comment by Wouter1** [comment]
But that did not resolve the NoSuchMethodError

**Comment by Wouter1** [comment]
Checking the code. In line 147 there is this

		header.position(OFF_SIGNATURE);

where OFF_SIGNATURE = 16

The error is weird, java does have a position(int) function built in? And there is nothing overriding java.nio (checked the jar).

**Comment by Wouter1** [comment]
Maybe this https://github.com/netty/netty/issues/9880 or https://stackoverflow.com/questions/48693695/java-nio-buffer-not-loading-clear-method-on-runtime
Is this a bug in the Eclipse built-in compiler?

**Comment by Wouter1** [comment]
Yes, it is a bug in the Eclipse compiler!
```
Version: 2021-09 (4.21.0)
Build id: 20210910-1417
```


 If I compile just with maven on java8 from commandline,  the tool just works fine.
